version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install -r requirements.txt
  post_build:
    commands:
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws elasticbeanstalk create-application-version --application-name Your-Application-Name --version-label Your-Version-Label --source-bundle S3Bucket="Your-S3-Bucket",S3Key="Your-Source-Bundle-Path"
